steps:
  # Install Terraform
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |
        terraform version
        terraform -chdir=$_ENV fmt 
        terraform -chdir=$_ENV init

  # Terraform plan
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform -chdir=$_ENV plan -out=tfplan

  # Terraform apply (uncomment if you want to apply changes)
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform -chdir=$_ENV apply -auto-approve tfplan

# Specify a timeout
timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
